# plugin manager

[[plugins]]
repo = 'Shougo/dein.vim'
rtp = ''

# colorscheme

[[plugins]]
repo = 'NLKNguyen/papercolor-theme'
on_event = ['VimEnter']
hook_post_source = '''
colo PaperColor
hi NonText ctermfg=bg guifg=bg
hi! link DiffAdd Tag
hi! link DiffChange Comment
hi! link DiffDelete WarningMsg
'''

# replacements

[[plugins]]
repo = 'tpope/vim-rsi'
on_event = ['VimEnter']

[[plugins]]
repo = 'kana/vim-repeat'
on_event = ['VimEnter']

[[plugins]]
repo = 'moll/vim-bbye'
on_event = ['VimEnter']
hook_post_source = '''
nm X :Bdelete<cr>
'''

[[plugins]]
repo = 'haya14busa/incsearch.vim'
on_event = ['VimEnter']
hook_post_source = '''
map f <plug>(incsearch-forward)
map F <plug>(incsearch-backward)
'''

[[plugins]]
repo = 'justinmk/vim-dirvish'
on_event = ['VimEnter']
hook_add = '''
let g:loaded_netrwPlugin=1
'''
hook_post_source = '''
au FileType dirvish cd %
au FileType dirvish nm <buffer> h -
au FileType dirvish nm <buffer> l <cr>
au FileType dirvish nm <buffer> ~ :Dirvish ~<cr>
'''

# utilities

[[plugins]]
repo = 'rliang/nvim-pygtk3'
build = 'make install'

[[plugins]]
repo = 'rliang/termedit.nvim'

[[plugins]]
repo = 'tpope/vim-eunuch'
on_event = ['VimEnter']
hook_post_source = '''
nm <leader>S :SudoWrite<cr>
'''

[[plugins]]
repo = 'mbbill/undotree'
on_event = ['VimEnter']
hook_add = '''
nm <leader>u :UndotreeToggle<cr>'
'''

[[plugins]]
repo = 'mhinz/vim-signify'
on_event = ['VimEnter']
hook_post_source = '''
hi! link SignColumn Normal
'''

# navigation

[[plugins]]
repo = 'ctrlpvim/ctrlp.vim'
on_event = ['VimEnter']
hook_add = '''
let g:ctrlp_map=''
nm <leader>h :CtrlPMRU<cr>
'''

[[plugins]]
repo = 'airblade/vim-rooter'
on_event = ['VimEnter']
hook_add = '''
let g:rooter_silent_chdir=1
let g:rooter_change_directory_for_non_project_files='current'
'''

# formatting

[[plugins]]
repo = 'terryma/vim-multiple-cursors'
on_event = ['VimEnter']

[[plugins]]
repo = 'junegunn/vim-easy-align'
on_event = ['VimEnter']

[[plugins]]
repo = 'sbdchd/neoformat'
on_event = ['VimEnter']

# text objects

[[plugins]]
repo = 'wellle/targets.vim'
on_event = ['VimEnter']

[[plugins]]
repo = 'tpope/vim-surround'
on_event = ['VimEnter']

[[plugins]]
repo = 'tpope/vim-commentary'
on_event = ['VimEnter']

[[plugins]]
repo = 'kana/vim-textobj-user'

[[plugins]]
repo = 'kana/vim-textobj-indent'
on_event = ['VimEnter']

[[plugins]]
repo = 'thinca/vim-textobj-between'
on_event = ['VimEnter']

[[plugins]]
repo = 'Julian/vim-textobj-variable-segment'
on_event = ['VimEnter']

[[plugins]]
repo = 'thalesmello/vim-textobj-methodcall'
on_event = ['VimEnter']

[[plugins]]
repo = 'tommcdo/vim-exchange'
on_event = ['VimEnter']

# completion

[[plugins]]
repo = 'Raimondi/delimitMate'
on_event = ['InsertEnter']
hook_add = '''
let g:delimitMate_expand_cr=1
let g:delimitMate_expand_space=1
let g:delimitMate_balance_matchpairs=1
'''

[[plugins]]
repo = 'SirVer/ultisnips'
on_event = ['InsertEnter']
if = "has('python3')"
hook_add = '''
let g:UltiSnipsExpandTrigger='<tab>'
let g:UltiSnipsJumpForwardTrigger='<tab>'
let g:UltiSnipsJumpBackwardTrigger='<s-tab>'
'''

[[plugins]]
repo = 'honza/vim-snippets'
depends = ['ultisnips']

[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_event = ['InsertEnter']
if = "has('python3')"
hook_add = '''
let g:deoplete#enable_at_startup=1
let g:deoplete#enable_smart_case=1
let g:deoplete#enable_refresh_always=1
'''
hook_post_source = '''
call deoplete#custom#set('_', 'matchers', ['matcher_full_fuzzy'])
'''

# languages

[[plugins]]
repo = 'sheerun/vim-polyglot'

[[plugins]]
repo = 'lervag/vimtex'
on_ft = ['tex', 'plaintex']

[[plugins]]
repo = 'poppyschmo/deoplete-latex'
on_ft = ['tex', 'plaintex']
depends = ['deoplete.nvim', 'vimtex']
hook_add = '''
let g:deoplete#sources#latex#include_misc=1
'''

[[plugins]]
repo = 'artur-shaik/vim-javacomplete2'
on_ft = ['java']
depends = ['deoplete.nvim']

[[plugins]]
repo = 'tweekmonster/deoplete-clang2'
on_ft = ['c', 'cpp']
depends = ['deoplete.nvim']

[[plugins]]
repo = 'zchee/deoplete-jedi'
on_ft = ['python']
depends = ['deoplete.nvim']
hook_add = '''
let g:deoplete#sources#jedi#show_docstring=1
'''

[[plugins]]
repo = 'carlitux/deoplete-ternjs'
on_ft = ['javascript', 'javascript.jsx']
depends = ['deoplete.nvim']
if = 'executable("npm")'
build = 'npm i tern'
hook_add = '''
let g:deoplete#sources#ternjs#tern_bin=
  \ g:dein_dir.'/../../carlitux/deoplete-ternjs/node_modules/.bin/tern'
'''
